---
apiVersion: v1
kind: Namespace
metadata:
  name: observability

---
apiVersion: v1
kind: Namespace
metadata:
  name: otel-automation

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-pipeline-automation
  namespace: otel-automation
  labels:
    app: otel-pipeline-automation
    component: automation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-pipeline-automation
  template:
    metadata:
      labels:
        app: otel-pipeline-automation
    spec:
      serviceAccountName: otel-automation-sa
      containers:
      - name: automation-service
        image: otel-pipeline-automation:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        - name: N8N_WEBHOOK_URL
          value: "http://n8n.n8n:5678/webhook/otel-automation"
        - name: LOKI_ENDPOINT
          value: "http://loki.observability:3100/loki/api/v1/push"
        - name: CLUSTER_NAME
          value: "kind-local"
        - name: OTEL_CONFIG_MAP_NAME
          value: "otel-collector-config"
        - name: OTEL_CONFIG_MAP_NAMESPACE
          value: "observability"
        - name: OTEL_COLLECTOR_NAMESPACE
          value: "observability"
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: otel-pipeline-automation
  namespace: otel-automation
  labels:
    app: otel-pipeline-automation
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: otel-pipeline-automation

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-automation-sa
  namespace: otel-automation

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-automation-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["opentelemetry.io"]
  resources: ["opentelemetrycollectors"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-automation-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-automation-role
subjects:
- kind: ServiceAccount
  name: otel-automation-sa
  namespace: otel-automation

---
# Mock OTEL Collector DaemonSet for testing
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-collector
  namespace: observability
  labels:
    app: otel-collector
spec:
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:0.88.0
        command:
          - "/otelcol-contrib"
          - "--config=/conf/otel-collector-config.yaml"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 13133
        - containerPort: 14250
        - containerPort: 14268
        - containerPort: 4317
        - containerPort: 4318
        volumeMounts:
        - name: config-vol
          mountPath: /conf
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: config-vol
        configMap:
          name: otel-collector-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: observability
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
      resource:
        attributes:
        - key: cluster.name
          value: kind-local
          action: insert

    exporters:
      logging:
        loglevel: debug
      loki:
        endpoint: "http://loki.observability:3100/loki/api/v1/push"

    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [batch, resource]
          exporters: [logging, loki]
        traces:
          receivers: [otlp]
          processors: [batch, resource]
          exporters: [logging]
        metrics:
          receivers: [otlp]
          processors: [batch, resource]
          exporters: [logging]

---
# Mock Loki deployment for testing
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:2.9.2
        args:
          - -config.file=/etc/loki/local-config.yaml
        ports:
        - containerPort: 3100
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: observability
spec:
  type: NodePort
  ports:
  - port: 3100
    targetPort: 3100
    nodePort: 31000
  selector:
    app: loki

---
# Mock n8n deployment for testing
apiVersion: v1
kind: Namespace
metadata:
  name: n8n
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: n8n-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/n8n-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-pvc
  namespace: n8n
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
      - name: n8n
        image: n8nio/n8n:latest
        ports:
        - containerPort: 5678
        env:
        - name: WEBHOOK_URL
          value: "http://localhost:5678"
        - name: N8N_SECURE_COOKIE
          value: "false"
        volumeMounts:
        - name: n8n-storage
          mountPath: /home/node/.n8n
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
      volumes:
      - name: n8n-storage
        persistentVolumeClaim:
          claimName: n8n-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: n8n
spec:
  type: NodePort
  ports:
  - port: 5678
    targetPort: 5678
    nodePort: 30567
  selector:
    app: n8n
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n-ingress
  namespace: n8n
spec:
  ingressClassName: nginx
  rules:
  - host: "n8n.lgthinq.com.local"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: n8n
            port:
              number: 5678
