---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-pipeline-automation
  namespace: default
  labels:
    app: otel-pipeline-automation
    component: automation-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: otel-pipeline-automation
  template:
    metadata:
      labels:
        app: otel-pipeline-automation
    spec:
      serviceAccountName: otel-automation-sa
      containers:
      - name: automation-service
        image: otel-pipeline-automation:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        - name: N8N_WEBHOOK_URL
          value: "http://n8n:5678/webhook/otel-automation"
        - name: LOKI_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: otel-config
              key: loki-endpoint
        - name: CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: otel-config
              key: cluster-name
        - name: OTEL_CONFIG_MAP_NAME
          value: "otel-collector-config"
        - name: OTEL_CONFIG_MAP_NAMESPACE
          value: "observability"
        - name: OTEL_COLLECTOR_NAMESPACE
          value: "observability"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: otel-pipeline-automation
  namespace: default
  labels:
    app: otel-pipeline-automation
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: otel-pipeline-automation

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-automation-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-automation-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-automation-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-automation-role
subjects:
- kind: ServiceAccount
  name: otel-automation-sa
  namespace: default

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
  namespace: default
data:
  loki-endpoint: "http://loki:3100/loki/api/v1/push"
  cluster-name: "production"