apiVersion: v1
kind: Namespace
metadata:
  name: ns-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-order-service
  namespace: ns-demo
  labels:
    app: demo-order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-order-service
  template:
    metadata:
      labels:
        app: demo-order-service
    spec:
      containers:
      - name: demo-order-service
        image: busybox
        command:
        - /bin/sh
        - -c
        - |
          i=0
          while true; do
            TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%S.000Z")
            ORDER_ID=$((i % 10000))
            MOD=$((i % 4))
            case $MOD in
              0) STATUS="200"; METHOD="GET"; URLPATH="/api/orders" ;;
              1) STATUS="201"; METHOD="POST"; URLPATH="/api/orders" ;;
              2) STATUS="400"; METHOD="PUT"; URLPATH="/api/orders/$ORDER_ID" ;;
              3) STATUS="500"; METHOD="DELETE"; URLPATH="/api/orders/$ORDER_ID" ;;
            esac
            DURATION=$((i % 500))
            LEVEL="info"
            if [ "$STATUS" = "500" ]; then LEVEL="error"; fi
            if [ "$STATUS" = "400" ]; then LEVEL="warn"; fi
            echo "{\"timestamp\":\"$TIMESTAMP\",\"level\":\"$LEVEL\",\"message\":{\"obj\":{\"method\":\"$METHOD\",\"path\":\"$URLPATH\",\"statusCode\":\"$STATUS\",\"responseTimeMs\":$DURATION}},\"metadata\":{\"app\":\"demo-order-service\",\"type\":\"httpResponse\",\"traceId\":\"trace-$ORDER_ID\"}}"
            i=$((i + 1))
            sleep 2
          done
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
          requests:
            memory: "32Mi"
            cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-order-service
  namespace: ns-demo
spec:
  selector:
    app: demo-order-service
  ports:
  - port: 8080
    targetPort: 8080
